<?xml version="1.0" encoding="utf-8"?><Database Name="ALUMNI" Class="DBAlumniDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-EFBO3C1\SQLSEVER;Initial Catalog=ALUMNI;User ID=admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ALUMNIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="[user]" Member="user" Type="System.String" DbType="NChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passwords" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.info" Member="infos">
    <Type Name="info">
      <Column Name="username" Type="System.String" DbType="NChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="job" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="startyear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="endyear" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>